#name : Pipeline Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Set up Java
              uses: actions/setup-java@v4
              with:
                java-version: '21'
                distribution: 'temurin'
            - name: Build with Maven
              run: mvn clean install -DskipTests
            - name: Run tests with Maven
              run: mvn test
            - name: Build Docker image
              run: |
                docker build -t myapp:latest .
            - name: Push Docker image to registry
              env:
                DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
              run: |
                echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
                docker tag myapp:latest $DOCKER_USERNAME/myapp:latest 
      
